#!/usr/bin/env node
/**
 * Bake real training data from ../data/runs/demo into src/data/real.ts.
 * The explainer page works fully offline on this baked snapshot.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const RUN = join(dirname(fileURLToPath(import.meta.url)), "../../data/runs/demo")
const OUT = join(dirname(fileURLToPath(import.meta.url)), "../src/data/real.ts")

function readJson(p) {
  return JSON.parse(readFileSync(p, "utf-8"))
}

function readJsonl(p) {
  if (!existsSync(p)) return []
  return readFileSync(p, "utf-8")
    .split("\n")
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l))
}

function slimGame(g) {
  return {
    id: g.id,
    kind: g.kind,
    iteration: g.iteration,
    board_size: g.board_size,
    win_len: g.win_len,
    result: g.result,
    meta: g.meta ?? {},
    moves: g.moves.map((m) => ({
      n: m.n, x: m.x, y: m.y, player: m.player, value: m.value,
      pi: m.pi, top: m.top,
    })),
  }
}

function main() {
  if (!existsSync(RUN)) {
    console.error(`run directory not found: ${RUN} (train a demo first)`)
    process.exit(1)
  }

  // --- a full self-play game from the latest iteration (hero + replay) ---
  const gameDirs = readdirSync(join(RUN, "games")).sort()
  const lastIt = gameDirs[gameDirs.length - 1]
  const firstFile = readdirSync(join(RUN, "games", lastIt)).sort()[0]
  const selfplayGame = slimGame(readJson(join(RUN, "games", lastIt, firstFile)))

  // hero move: the most "decided" mid/late-game move (top-1 visit share,
  // restricted to n >= 8 so the board is visually interesting)
  let heroIndex = 0
  let heroScore = -1
  selfplayGame.moves.forEach((m, i) => {
    if (m.n < 8) return
    const p = m.top?.[0]?.prob ?? 0
    if (p > heroScore) {
      heroScore = p
      heroIndex = i
    }
  })

  // --- empty-board first-move pi per iteration (policy evolution, real) ---
  const firstMovePi = []
  for (const it of gameDirs) {
    const f = readdirSync(join(RUN, "games", it)).sort()[0]
    const g = readJson(join(RUN, "games", it, f))
    const m0 = g.moves[0]
    firstMovePi.push({ iteration: g.iteration, pi: m0.pi, top: m0.top, value: m0.value })
  }

  // --- metrics ---
  const metrics = readJsonl(join(RUN, "metrics.jsonl")).map((r) => ({
    iteration: r.iteration,
    loss: r.loss,
    policy_loss: r.policy_loss,
    value_loss: r.value_loss,
    buffer: r.buffer,
    samples_total: r.samples_total,
    arena_vs_best: r.arena_vs_best,
    arena_vs_baseline: r.arena_vs_baseline,
    best_iteration: r.best_iteration,
  }))

  // --- one real arena game (vs best, latest arena iteration) ---
  let arenaGame = null
  const arenaRoot = join(RUN, "arena")
  if (existsSync(arenaRoot)) {
    const aIts = readdirSync(arenaRoot).sort()
    for (let i = aIts.length - 1; i >= 0 && !arenaGame; i--) {
      const f = readdirSync(join(arenaRoot, aIts[i])).filter((x) => x.startsWith("ar_")).sort()[0]
      if (f) arenaGame = slimGame(readJson(join(arenaRoot, aIts[i], f)))
    }
  }

  // --- arena reports from the event stream ---
  const arenaReports = readJsonl(join(RUN, "events.jsonl"))
    .filter((e) => e.type === "arena_end")
    .map((e) => ({
      iteration: e.data.iteration,
      opponent: e.data.opponent,
      win_rate: e.data.win_rate,
      wins: e.data.wins,
      losses: e.data.losses,
      draws: e.data.draws,
      promoted: e.data.promoted,
    }))

  const banner = `/** GENERATED by scripts/export-data.mjs from data/runs/demo.
 *  Do not edit by hand; re-run \`npm run export-data\` to refresh.
 *  Snapshot of REAL training data used throughout the page. */
`
  const body = `${banner}
export interface BakedTop { action: number; x: number; y: number; visits: number; prob: number }
export interface BakedMove { n: number; x: number; y: number; player: number; value: number; pi: number[]; top: BakedTop[] }
export interface BakedGame {
  id: string; kind: string; iteration: number; board_size: number; win_len: number
  result: number; meta: { black?: string; white?: string; opponent?: string | null }
  moves: BakedMove[]
}
export interface FirstMovePi { iteration: number; pi: number[]; top: BakedTop[]; value: number }
export interface MetricRow {
  iteration: number; loss: number | null; policy_loss: number | null; value_loss: number | null
  buffer: number; samples_total: number
  arena_vs_best: { win_rate_a: number; wins_a: number; wins_b: number; draws: number; promoted: boolean } | null
  arena_vs_baseline: { win_rate_a: number; wins_a: number; wins_b: number; draws: number; promoted: boolean } | null
  best_iteration: number
}
export interface ArenaReport {
  iteration: number; opponent: string; win_rate: number | null
  wins: number; losses: number; draws: number; promoted: boolean
}
export interface RealData {
  selfplayGame: BakedGame
  heroIndex: number
  firstMovePi: FirstMovePi[]
  metrics: MetricRow[]
  arenaGame: BakedGame | null
  arenaReports: ArenaReport[]
}

export const REAL: RealData = ${JSON.stringify(
    { selfplayGame, heroIndex, firstMovePi, metrics, arenaGame, arenaReports },
    null,
    0,
  )}
`

  mkdirSync(dirname(OUT), { recursive: true })
  writeFileSync(OUT, body)
  const kb = (body.length / 1024).toFixed(1)
  console.log(`baked ${OUT} (${kb} KB): hero=move#${heroIndex} of ${selfplayGame.id}, ` +
    `${firstMovePi.length} iterations, arena game: ${arenaGame ? arenaGame.id : "none"}`)
}

main()
