import { chromium } from "playwright"
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1400, height: 950 } })
await page.goto("http://localhost:4173", { waitUntil: "networkidle" })
const ch4 = page.locator("#ch-4")
await ch4.scrollIntoViewIfNeeded()
await page.waitForTimeout(400)
const btn = (name) => ch4.locator("button", { hasText: name }).first()
await btn("跑到 200").click()
await page.waitForTimeout(500)
await ch4.locator(".figure").first().screenshot({ path: "scripts/shot-ch4-tree-200sims.png" })
// ch1 button label spacing
const ch1 = page.locator("#ch-1")
await ch1.scrollIntoViewIfNeeded()
await page.waitForTimeout(300)
await ch1.locator("button.btn.primary").click()
await page.waitForTimeout(200)
await ch1.locator("button.btn.primary").screenshot({ path: "scripts/shot-ch1-btn.png" })
console.log("saved")
await browser.close()
